baseURL = "http://basti.rocks/"
languageCode = "DE"
defaultContentLanguage = "de"
title = "Basti rocks hugo"
copyright = "CC-BY-4.0 basti-schr"
theme = "basics"

[params]
    author = "Sebastian"
    github = "basti-schr"
